//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityWindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacto
    {
        public int id_contacto { get; set; }
        public string contacto_nombre { get; set; }
        public string contacto_correo { get; set; }
        public string contacto_mensaje { get; set; }
        public System.DateTime contacto_fecha { get; set; }
    }
}
