//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityWindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_usuario
    {
        public int id_detalle_usuario { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public string detalle_usuario_biografia { get; set; }
        public string detalle_usuario_tipo_cliente { get; set; }
        public string detalle_usuario_tipo_inmueble { get; set; }
        public string detalle_usuario_especialidad { get; set; }
        public string detalle_usuario_idioma { get; set; }
    
        public virtual servicio servicio { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
