//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityWindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class inmueble
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inmueble()
        {
            this.creditoes = new HashSet<credito>();
            this.favoritoes = new HashSet<favorito>();
            this.fotoes = new HashSet<foto>();
        }
    
        public int id_inmueble { get; set; }
        public int id_usuario { get; set; }
        public int id_operacion { get; set; }
        public int id_tipo_inmueble { get; set; }
        public string inmueble_titulo { get; set; }
        public string inmueble_descripcion { get; set; }
        public decimal inmueble_monto { get; set; }
        public Nullable<decimal> inmueble_subasta { get; set; }
        public string inmueble_codigo { get; set; }
        public string inmueble_terreno { get; set; }
        public string inmueble_construido { get; set; }
        public int inmueble_habitaciones { get; set; }
        public decimal inmueble_baños { get; set; }
        public int inmueble_cocina { get; set; }
        public int inmueble_sala { get; set; }
        public int inmueble_comedor { get; set; }
        public int inmueble_jardin { get; set; }
        public int inmueble_terraza { get; set; }
        public int inmueble_alberca { get; set; }
        public int inmueble_capacidad_autos { get; set; }
        public string inmueble_calle { get; set; }
        public string inmueble_numero_exterior { get; set; }
        public string inmueble_numero_interior { get; set; }
        public string inmueble_colonia { get; set; }
        public int inmueble_codigo_postal { get; set; }
        public string inmueble_localidad { get; set; }
        public string inmueble_municipio { get; set; }
        public string inmueble_estado { get; set; }
        public string inmueble_pais { get; set; }
        public decimal inmueble_latitud { get; set; }
        public decimal inmueble_longitud { get; set; }
        public System.DateTime inmueble_fecha_registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<credito> creditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorito> favoritoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foto> fotoes { get; set; }
        public virtual operacion operacion { get; set; }
        public virtual tipo_inmueble tipo_inmueble { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
